name: Build+Test

on:
  push:
    branches: [ main ]
    tags: "v*"
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                build: [macos-latest, linux, win-msvc, win32-msvc]
                include:
                    - project_name: laggar
                    - build: linux
                      os: ubuntu-latest
                      name: x86_64-unknown-linux-musl
                    - build: macos-latest
                      os: macos-latest
                      name: x86_64-apple-darwin
                    - build: win-msvc
                      os: windows-2019
                      name: x86_64-pc-windows-msvc
                    - build: win32-msvc
                      os: windows-2019
                      name: i686-pc-windows-msvc
        steps:
          - uses: actions/cache@v2
            name: Cache
            with:
                path: |
                    ~/.cargo/registry
                    ~/.cargo/git
                    target
                key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
                  
          - uses: actions/checkout@v2
        
          - name: Build
            run: cargo build --verbose
        
          - name: Run tests
            run: cargo test --verbose
